CLI: Provide Typescript templates for Preact
storybooks/storybook pull request #21689
Opened 2023-03-20 14:04 UTC by yannbf

Closes #

## What I did

The CLI only contained JS templates for Preact. This PR adds Typescript (and 4.9) to it.

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template preact-vite/default-ts`
2. It should contain typescript stories

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-03-20 14:30 UTC, yannbf commented on code/renderers/preact/template/cli/ts-4-9/Header.stories.ts
> +    // @ts-expect-error TODO seems like props extraction in Story type is not correct
@kasperpeulen could you assist on this one? Thanks <3

2023-08-04 09:46 UTC, kasperpeulen commented on code/renderers/preact/template/cli/ts-4-9/Header.stories.ts
> +type Story = StoryObj<typeof meta>;
We don't support this yet in Preact!

2023-08-04 09:46 UTC, kasperpeulen commented on code/renderers/preact/template/cli/ts-4-9/Header.stories.ts
> +type Story = StoryObj<typeof meta>;
Should be `StoryObj<HeaderProps>`

2023-08-04 09:47 UTC, kasperpeulen requested changes
Not sure, if we should do this, maybe we should first make the types of Preact aligned with the other renderers.

2024-11-25 14:29 UTC, closed without merging