fixes
storybooks/storybook pull request #25018
Opened 2023-11-28 16:13 UTC by ndelangen

Closes #

## What I did

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2023-11-28 18:33 UTC, JReinhold commented on code/addons/docs/template/stories/stories-mdx/raw-source.stories.mdx
> +</Canvas>
This test case doesn't make sense anymore, since MDX Stories won't be supported in 8.0 anyway.

2023-11-28 18:35 UTC, JReinhold requested changes
I think the `resourceQuery` itself is fine, but I expect we can test this in a regular story, we don't need to test this through MDX.

2023-11-28 19:55 UTC, ndelangen commented
@JReinhold do you have a suggestion on how to make this story only function for a specific set of sandboxes? none-svelte and non-angular?

Alternatively, any suggestions why they seem to not work for those frameworks?

2023-11-29 10:38 UTC, valentinpalkovic commented
@ndelangen For Angular, it is pretty easy to answer. Our babel-loader is not used in Angular projects. Instead, Angular's babel-loader is used.

2024-03-26 09:34 UTC, closed without merging